#!/bin/bash
sudo apt-get install cmake gcc g++ git pkg-config ragel libasound2-dev libssl-dev libglib2.0-dev libconfig-dev libpango1.0-dev libgl1-mesa-dev libevent-dev libgtk2.0-dev libxrandr-dev libxrender-dev libxcursor-dev libv4l-dev libgles2-mesa-dev libavcodec-dev libva-dev libvdpau-dev libdrm-dev libpulse-dev libjack-jackd2-dev libsoxr-dev
cd ~/Downloads
git clone https://github.com/i-rinat/freshplayerplugin.git
cd ./freshplayerplugin
mkdir build
cd build
cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo ..
make
sudo cp libfreshwrapper-flashplayer.so /usr/lib/mozilla/plugins/
cd ../../
rm -rf ./freshplayerplugin
sudo apt-get remove --purge cmake ragel libasound2-dev libssl-dev libconfig-dev libevent-dev libv4l-dev libgles2-mesa-dev libavcodec-dev libva-dev libvdpau-dev libpulse-dev libjack-jackd2-dev libsoxr-dev
sudo apt-get autoremove --purge
sudo apt-get install libsoxr0 pepperflashplugin-nonfree
sudo apt-get clean
